# Generated by Django 4.1 on 2022-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coverImage', models.ImageField(upload_to='blog')),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('firstParagraph', models.TextField()),
                ('secondParagraph', models.TextField(null=True)),
                ('thirdParagraph', models.TextField(null=True)),
                ('conclusion', models.TextField()),
                ('image1', models.ImageField(upload_to='blog')),
                ('image2', models.ImageField(upload_to='blog')),
                ('image3', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
