# Generated by Django 4.1 on 2022-08-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coverImage', models.ImageField(upload_to='talent')),
                ('height', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('bust', models.IntegerField()),
                ('shoe', models.IntegerField()),
                ('dress', models.IntegerField()),
                ('eye', models.CharField(max_length=255)),
                ('hair', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent/img')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.talent')),
            ],
        ),
    ]
